# This workflow will install Python dependencies, run tests and lint with a variety of Python versions
# For more information see: https://help.github.com/actions/language-and-framework-guides/using-python-with-github-actions

name: Tests

on:
    push:
        branches:
            - master
    pull_request:
    workflow_dispatch:

concurrency:
    group: ${{ github.workflow }}-${{ github.head_ref || github.run_id }}
    cancel-in-progress: true

jobs:
    build:
        name: ${{ matrix.os }} (py ${{ matrix.version }}${{ matrix.special }})
        runs-on: ${{ matrix.os }}
        strategy:
            fail-fast: false
            matrix:
                os: [ubuntu-latest, macos-latest]
                version: ["3.7", "3.8", "3.9", "3.10"]
                special: [""]
                include:
                    -   os: ubuntu-latest
                        special: "; pre-release"
                        version: "3.10"

        steps:
            -   uses: actions/checkout@v3

            -   name: Set up Python
                uses: actions/setup-python@v4
                with:
                    python-version: ${{ matrix.version }}

            -   name: Install dependencies
                run: |
                    case "${{ matrix.special }}" in
                        "; pre-release")
                            pip install -e .[test] --pre
                            pip install git+https://github.com/SCM-NV/PLAMS@master --upgrade
                            pip install git+https://github.com/SCM-NV/qmflows@master --upgrade
                            pip install git+https://github.com/nlesc-nano/CAT@master --upgrade
                            ;;
                        *)
                            pip install -e .[test] ;;
                    esac

            -   name: Install MongoDB
                if: matrix.os == 'ubuntu-latest'
                uses: supercharge/mongodb-github-action@1.9.0

            -   name: Info MongDB
                if: matrix.os == 'ubuntu-latest'
                run: mongo --version

            -   name: Python info
                run: |
                    which python
                    python --version

            -   name: Installed packages
                run: pip list

            -   name: Run tests
                run: pytest -m "not slow"

            -   name: Run codecov
                uses: codecov/codecov-action@v3
                with:
                    file: ./coverage.xml
                    name: codecov-umbrella

    Linting:
        runs-on: ubuntu-latest
        steps:
            -   uses: actions/checkout@v3

            -   name: Set up Python on ubuntu-latest
                uses: actions/setup-python@v4
                with:
                    python-version: '3.x'

            -   name: Install dependencies
                run: |
                    pip install -e .
                    pip install "flake8>=3.8.0" "pydocstyle>=5.0.0" mypy nano-CAT

            -   name: Python info
                run: |
                    which python
                    python --version

            -   name: Installed packages
                run: pip list

            -   name: Run flake8
                run: flake8 dataCAT tests

            -   name: Run pydocstyle
                run: pydocstyle dataCAT

            -   name: Run mypy
                run: mypy dataCAT
                continue-on-error: true
